### ISSUE TITLE
Filter component using CachetHQ tags (or groups)

### ISSUE THREAD

**Issue by renebarbosafl** [oxyno-zeta/prometheus-cachethq#4]
We have several components with the same name (for example "API") in multiple groups. 
When we send an update to the component searching for the name, all of them are being updated.

It would be nice to find the components using tags.

**Comment by oxyno-zeta** [comment]
Hello !

First of all, thanks for your good first issue. I must admit that I'm surprised that this project is used by someone else :) .

I'm facing a problem with your request: the golang client I'm using in this project haven't the support for tags (and seems not maintained unfortunately...). 

So I can imagine two solutions here:

1)
- Redoing a golang client to call CachetHQ instances in order to add the support for Tags.
- Add a tag list filter in the configuration for groups

But: How to manage the fact that multiple groups have the same set of tags ?

2)
- Add a property inside the component configuration to select the component inside a group:

```yaml
   component:
      name: API
      group: FAKE1 # optional
      status: PARTIAL_OUTAGE
```

- Retreive the group id property by searching groups by name
- Search component filtering by name AND groupId


I must admit that I'm more in favour of the solution 2. Do you see any problems with that ?

**Comment by renebarbosafl** [comment]
Hello Alexandre!

Thanks for your prompt answer! 
Yeah we are trying to use your project with our monitoring system and so far it's promising. :) 

About your proposal.. I think the solution #2 will work just fine, even without the support for tags. In our example:

Group: CustomerA
Component: API

Group: CustomerB
Component API

So we just need to use the "group: CustomerA" and "name: API" in our component declaration and it will work!
Nice!

**Comment by oxyno-zeta** [comment]
I've just released the 1.1.0 with this feature. Thanks for your feature.

Tell me if everything is ok.

**Comment by renebarbosafl** [comment]
Testing this right now with this config:

```
  - component:
      name: API
      group: Alagoas
      status: PERFORMANCE_ISSUES
    alerts:
      - name: ApiPerformance
```
We forced an alert and our components weren't updated. 
Log from alertmanager:

level=error ts=2020-09-03T15:11:34.755Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="cachethq-receiver/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 404: http://prom-cachethq:8080/prometheus/webhook"

For some reason it's not finding the components using Group and name.

**Comment by oxyno-zeta** [comment]
Hello !

The configuration isn't valid. The key is "groupName" and not "group". Your key has been ignored.
I've changed the key from the upper example. Why ? Because if in future we need to have a key called "groupID", it will be clear ;-).

Hope this will work now.

PS: sorry for the short answer, I'm on my phone :smiley:

**Comment by renebarbosafl** [comment]
Awesome, worked like a charm!
Thank you.
